name: deploy dev branch

# on:
#   push:
#     branches:
#       - dev

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Repo Checkout
        uses: action/checkout@v4
      - name: Deploy in ec2
        uses: appleboy/ssh-action@v1
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.SSHKEY }}
          port: ${{ secrets.PORT }}
          script: "./var/www/sajic.marce1in.com.br/.github/scripts/deploy.sh"
