name: Laravel

on:
  workflow_dispatch:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  laravel-tests:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v5

    - name: Setup Node
      uses: actions/setup-node@v6
      with:
        node-version: '24'

    - name: Setup php
      uses: shivammathur/setup-php@v2
      with:
        php-version: '8.4'

    - name: "Install project depedencies"
      run: \
        "composer install --no-dev --no-interaction --prefer-dist --optimize-autoloader --no-scripts"
        "php artisan package:discover --ansi"
        "npm ci"

    - name: "Build front-end"
      run: "npm run build:ssr"

